@extends('layouts.app')
@section('title', 'Relatórios')
@section('eyebrow', 'ANÁLISE')
@section('page_title', 'Relatórios financeiros')
@section('page_subtitle', 'Encontre padrões e entenda seus resultados por período.')
@section('page_content')
<div class="card border-0 shadow-sm mb-4"><div class="card-body"><form method="get" class="row g-3 align-items-end"><div class="col-sm-6 col-xl-2"><label for="from" class="form-label">De</label><input id="from" type="date" name="from" value="{{ $filters['from']??'' }}" class="form-control"></div><div class="col-sm-6 col-xl-2"><label for="to" class="form-label">Até</label><input id="to" type="date" name="to" value="{{ $filters['to']??'' }}" class="form-control"></div><div class="col-md-5 col-xl-3"><label for="account_id" class="form-label">Conta</label><select id="account_id" name="account_id" class="form-select"><option value="">Todas</option>@foreach($accounts as $account)<option value="{{ $account['id'] }}" @selected(($filters['account_id']??'')==$account['id'])>{{ $account['name'] }}</option>@endforeach</select></div><div class="col-md-5 col-xl-3"><label for="category_id" class="form-label">Categoria</label><select id="category_id" name="category_id" class="form-select"><option value="">Todas</option>@foreach($categories as $category)<option value="{{ $category['id'] }}" @selected(($filters['category_id']??'')==$category['id'])>{{ $category['name'] }}</option>@endforeach</select></div><div class="col-md-2 col-xl-2 d-grid"><button class="btn btn-primary"><i class="bi bi-funnel me-1"></i> Filtrar</button></div></form></div></div>

<div class="row g-3 mb-4">@foreach([['Receitas',$report['income'],'success'],['Despesas',$report['expenses'],'danger'],['Resultado',$report['result'],$report['result']>=0?'primary':'warning']] as [$label,$value,$theme])<div class="col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><span class="small text-body-secondary">{{ $label }}</span><div class="h3 mt-2 mb-0 text-{{ $theme }}"><x-money :value="$value" /></div></div></div></div>@endforeach</div>

<div class="row g-4 mb-4"><div class="col-xl-7"><div class="card border-0 shadow-sm h-100"><div class="card-header border-0 bg-transparent"><h2 class="h5 mb-0">Evolução mensal</h2></div><div class="card-body"><div data-apexchart data-apexchart-config="{{ json_encode($trendChart) }}"></div></div></div></div>
<div class="col-xl-5"><div class="card border-0 shadow-sm h-100"><div class="card-header border-0 bg-transparent"><h2 class="h5 mb-0">Despesas por categoria</h2></div><div class="card-body">@if($report['byCategory']->isNotEmpty())<div data-apexchart data-apexchart-config="{{ json_encode($categoryChart) }}"></div>@else<div class="text-center py-5 text-body-secondary"><i class="bi bi-pie-chart display-5"></i><p class="mt-3">Sem despesas no período.</p></div>@endif</div></div></div></div>

<div class="card border-0 shadow-sm"><div class="card-header bg-transparent border-0"><h2 class="h5 mb-0">Detalhamento por categoria</h2></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Categoria</th><th class="text-end">Total</th><th class="text-end">Participação</th></tr></thead><tbody>@forelse($report['byCategory'] as $item)<tr><td>{{ $item['name'] }}</td><td class="text-end"><x-money :value="$item['amount']" /></td><td class="text-end">{{ $report['expenses'] ? number_format($item['amount']/$report['expenses']*100,1,',','.') : 0 }}%</td></tr>@empty<tr><td colspan="3" class="text-center py-4">Nenhum dado para exibir.</td></tr>@endforelse</tbody></table></div></div>
@endsection
