@extends('layouts.app')
@php($editing = (bool) $purchase)
@section('title', $editing ? 'Editar compra' : 'Nova compra')
@section('eyebrow', 'CARTÃO DE CRÉDITO')
@section('page_title', $editing ? 'Editar compra' : 'Nova compra no '.$card['name'])
@section('page_subtitle', 'O total compromete o limite agora; cada parcela entra no orçamento de sua fatura.')
@section('page_actions')<a href="{{ $editing ? route('card-purchases.show', $purchase['id']) : route('credit-cards.show', $card['id']) }}" class="btn btn-outline-secondary">Cancelar</a>@endsection
@section('page_content')
<div class="row"><div class="col-xl-8"><div class="card border-0 shadow-sm"><div class="card-body p-4"><form method="post" action="{{ $editing ? route('card-purchases.update', $purchase['id']) : route('credit-cards.purchases.store', $card['id']) }}">@csrf @if($editing)@method('put')@endif
<div class="row g-3"><div class="col-md-8"><label for="description" class="form-label">Descrição</label><input id="description" name="description" value="{{ old('description', $purchase['description'] ?? '') }}" class="form-control @error('description') is-invalid @enderror" required><x-field-error name="description" /></div><div class="col-md-4"><label for="purchase_date" class="form-label">Data da compra</label><input type="date" id="purchase_date" name="purchase_date" value="{{ old('purchase_date', $purchase['purchase_date'] ?? now()->toDateString()) }}" class="form-control @error('purchase_date') is-invalid @enderror" required><x-field-error name="purchase_date" /></div>
<div class="col-md-4"><label for="total_amount" class="form-label">Valor total</label><div class="input-group"><span class="input-group-text">R$</span><input id="total_amount" name="total_amount" value="{{ old('total_amount', $purchase ? number_format($purchase['total_amount']/100, 2, ',', '') : '') }}" class="form-control @error('total_amount') is-invalid @enderror" required></div><x-field-error name="total_amount" /><div class="form-text">Disponível: <x-money :value="$card['available_limit']" />.</div></div><div class="col-md-4"><label for="installments_count" class="form-label">Parcelas</label><input type="number" min="1" max="120" id="installments_count" name="installments_count" value="{{ old('installments_count', $purchase['installments_count'] ?? 1) }}" class="form-control @error('installments_count') is-invalid @enderror" required><x-field-error name="installments_count" /></div><div class="col-md-4"><label for="category_id" class="form-label">Categoria</label><select id="category_id" name="category_id" class="form-select @error('category_id') is-invalid @enderror" required><option value="">Selecione</option>@foreach($categories as $category)<option value="{{ $category['id'] }}" @selected(old('category_id', $purchase['category_id'] ?? '') == $category['id'])>{{ $category['name'] }}</option>@endforeach</select><x-field-error name="category_id" /></div>
<div class="col-12"><div class="alert alert-info mb-0"><i class="bi bi-info-circle me-2"></i>As parcelas são despesas nas datas de fechamento das respectivas faturas. O pagamento da fatura será apenas uma transferência da conta bancária.</div></div></div>
<div class="d-flex justify-content-end gap-2 mt-4"><a href="{{ $editing ? route('card-purchases.show', $purchase['id']) : route('credit-cards.show', $card['id']) }}" class="btn btn-light">Cancelar</a><button class="btn btn-primary">{{ $editing ? 'Salvar e recalcular parcelas' : 'Registrar compra' }}</button></div></form></div></div></div></div>
@endsection
