@extends('layouts.app')
@section('title', $purchase['description'])
@section('eyebrow', 'COMPRA NO CARTÃO')
@section('page_title', $purchase['description'])
@section('page_subtitle', $purchase['card_name'].' · '.$purchase['category_name'])
@section('page_actions')@if($purchase['can_change'])<a href="{{ route('card-purchases.edit', $purchase['id']) }}" class="btn btn-primary"><i class="bi bi-pencil me-1"></i>Editar</a>@endif<a href="{{ route('credit-cards.show', $purchase['credit_card_id']) }}" class="btn btn-outline-secondary">Ver cartão</a>@endsection
@section('page_content')
<div class="row g-4"><div class="col-lg-8"><div class="card border-0 shadow-sm"><div class="card-body p-4"><div class="row g-3 mb-4"><div class="col-sm-4"><div class="small text-body-secondary">Valor total</div><div class="h4"><x-money :value="$purchase['total_amount']" /></div></div><div class="col-sm-4"><div class="small text-body-secondary">Data da compra</div><strong>{{ \Carbon\Carbon::parse($purchase['purchase_date'])->format('d/m/Y') }}</strong></div><div class="col-sm-4"><div class="small text-body-secondary">Parcelamento</div><strong>{{ $purchase['installments_count'] }}x</strong></div></div>
<h2 class="h6">Cronograma de parcelas</h2><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Parcela</th><th>Fatura</th><th>Fechamento</th><th>Vencimento</th><th class="text-end">Valor</th></tr></thead><tbody>@foreach($purchase['installments'] as $installment)<tr><td>{{ $installment['number'] }}/{{ $purchase['installments_count'] }}</td><td><a href="{{ route('credit-cards.show', ['credit_card'=>$purchase['credit_card_id'],'statement'=>$installment['statement_month']]) }}">{{ \Carbon\Carbon::createFromFormat('Y-m-d', $installment['statement_month'].'-01')->translatedFormat('M/Y') }}</a></td><td>{{ \Carbon\Carbon::parse($installment['closing_date'])->format('d/m/Y') }}</td><td>{{ \Carbon\Carbon::parse($installment['due_date'])->format('d/m/Y') }}</td><td class="text-end"><x-money :value="$installment['amount']" /></td></tr>@endforeach</tbody></table></div></div></div></div>
<div class="col-lg-4"><div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h6">Regras desta compra</h2><p class="small text-body-secondary">Cada parcela aparece como despesa no mês da fatura e participa dos relatórios e orçamentos. O valor total compromete o limite até os pagamentos.</p>@if($purchase['can_change'])<form method="post" action="{{ route('card-purchases.destroy', $purchase['id']) }}" data-confirm="Excluir a compra e todas as parcelas futuras?">@csrf @method('delete')<button class="btn btn-outline-danger w-100">Excluir compra</button></form>@else<div class="alert alert-secondary mb-0"><i class="bi bi-lock me-1"></i>A compra está bloqueada porque uma fatura fechou ou recebeu pagamento.</div>@endif</div></div></div></div>
@endsection
