@extends('layouts.app')
@php
    $statement = $card['statement'];
    $monthDate = \Carbon\Carbon::createFromFormat('Y-m-d', $statement['month'].'-01');
    $previousMonth = $monthDate->copy()->subMonth()->format('Y-m');
    $nextMonth = $monthDate->copy()->addMonth()->format('Y-m');
    $statusClass = ['open'=>'text-bg-primary','closed'=>'text-bg-warning','partially_paid'=>'text-bg-info','paid'=>'text-bg-success'][$statement['status']];
@endphp
@section('title', $card['name'])
@section('eyebrow', 'CARTÃO DE CRÉDITO')
@section('page_title', $card['name'])
@section('page_subtitle', $card['network'].' · fechamento dia '.$card['closing_day'].' · vencimento dia '.$card['due_day'])
@section('page_actions')@if(!$card['archived'])<a href="{{ route('credit-cards.purchases.create', $card['id']) }}" class="btn btn-primary"><i class="bi bi-cart-plus me-1"></i> Nova compra</a>@endif<a href="{{ route('credit-cards.edit', $card['id']) }}" class="btn btn-outline-secondary">Editar cartão</a>@endsection
@section('page_content')
<div class="row g-3 mb-4"><div class="col-sm-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="text-body-secondary small">Limite total</div><div class="h4 mb-0"><x-money :value="$card['credit_limit']" /></div></div></div></div><div class="col-sm-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="text-body-secondary small">Limite usado</div><div class="h4 mb-0"><x-money :value="$card['used_limit']" /></div></div></div></div><div class="col-sm-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="text-body-secondary small">Disponível</div><div class="h4 text-success mb-0"><x-money :value="$card['available_limit']" /></div></div></div></div><div class="col-sm-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="text-body-secondary small">Fatura em aberto</div><div class="h4 mb-0"><x-money :value="$statement['outstanding']" /></div></div></div></div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-header bg-transparent d-flex justify-content-between align-items-center"><a class="btn btn-sm btn-outline-secondary" aria-label="Fatura anterior" href="{{ route('credit-cards.show', ['credit_card'=>$card['id'],'statement'=>$previousMonth]) }}"><i class="bi bi-chevron-left"></i></a><div class="text-center"><h2 class="h5 mb-1">Fatura de {{ $monthDate->translatedFormat('F/Y') }}</h2><span class="badge {{ $statusClass }}">{{ $statement['status_label'] }}</span></div><a class="btn btn-sm btn-outline-secondary" aria-label="Próxima fatura" href="{{ route('credit-cards.show', ['credit_card'=>$card['id'],'statement'=>$nextMonth]) }}"><i class="bi bi-chevron-right"></i></a></div>
<div class="card-body"><div class="row g-3 mb-4"><div class="col-md-3"><div class="small text-body-secondary">Período</div>{{ \Carbon\Carbon::parse($statement['period_start'])->format('d/m/Y') }} a {{ \Carbon\Carbon::parse($statement['closing_date'])->format('d/m/Y') }}</div><div class="col-md-3"><div class="small text-body-secondary">Vencimento</div>{{ \Carbon\Carbon::parse($statement['due_date'])->format('d/m/Y') }}</div><div class="col-md-2"><div class="small text-body-secondary">Total</div><strong><x-money :value="$statement['total']" /></strong></div><div class="col-md-2"><div class="small text-body-secondary">Pago</div><strong class="text-success"><x-money :value="$statement['paid']" /></strong></div><div class="col-md-2"><div class="small text-body-secondary">Pendente</div><strong><x-money :value="$statement['outstanding']" /></strong></div></div>
<div class="table-responsive"><table class="table align-middle"><thead><tr><th>Compra</th><th>Categoria</th><th>Parcela</th><th class="text-end">Valor</th></tr></thead><tbody>@forelse($statement['installments'] as $installment)<tr><td><a class="text-body fw-semibold text-decoration-none" href="{{ route('card-purchases.show', $installment['purchase_id']) }}">{{ $installment['description'] }}</a><div class="small text-body-secondary">Compra em {{ \Carbon\Carbon::parse($installment['purchase_date'])->format('d/m/Y') }}</div></td><td>{{ $installment['category_name'] }}</td><td>{{ $installment['number'] }}/{{ $installment['total_installments'] }}</td><td class="text-end"><x-money :value="$installment['amount']" /></td></tr>@empty<tr><td colspan="4" class="text-center py-4 text-body-secondary">Nenhuma parcela nesta fatura.</td></tr>@endforelse</tbody></table></div></div></div>
<div class="row g-4"><div class="col-lg-7"><div class="card border-0 shadow-sm"><div class="card-header bg-transparent"><h2 class="h6 mb-0">Pagamentos</h2></div><div class="card-body">@forelse($statement['payments'] as $payment)<div class="d-flex justify-content-between align-items-center border-bottom py-2"><div><strong><x-money :value="$payment['amount']" /></strong><div class="small text-body-secondary">{{ $payment['source_account_name'] }} · {{ \Carbon\Carbon::parse($payment['payment_date'])->format('d/m/Y') }}</div></div><form method="post" action="{{ route('card-statement-payments.destroy', $payment['id']) }}" data-confirm="Excluir este pagamento e a transferência vinculada?">@csrf @method('delete')<button class="btn btn-sm btn-outline-danger" aria-label="Excluir pagamento"><i class="bi bi-trash"></i></button></form></div>@empty<p class="text-body-secondary mb-0">Nenhum pagamento registrado.</p>@endforelse</div></div></div>
<div class="col-lg-5">@if($statement['status'] !== 'open' && $statement['outstanding'] > 0 && $statement['id'])<div class="card border-0 shadow-sm"><div class="card-header bg-transparent"><h2 class="h6 mb-0">Pagar fatura</h2></div><div class="card-body"><form method="post" action="{{ route('card-statements.payments.store', $statement['id']) }}">@csrf<div class="mb-3"><label for="source_account_id" class="form-label">Conta de origem</label><select id="source_account_id" name="source_account_id" class="form-select @error('source_account_id') is-invalid @enderror" required>@foreach($paymentAccounts as $account)<option value="{{ $account['id'] }}" @selected(old('source_account_id', $card['default_payment_account_id']) == $account['id'])>{{ $account['name'] }}</option>@endforeach</select><x-field-error name="source_account_id" /></div><div class="mb-3"><label for="amount" class="form-label">Valor</label><div class="input-group"><span class="input-group-text">R$</span><input id="amount" name="amount" value="{{ old('amount', number_format($statement['outstanding']/100, 2, ',', '')) }}" class="form-control @error('amount') is-invalid @enderror" required></div><x-field-error name="amount" /></div><div class="mb-3"><label for="payment_date" class="form-label">Data</label><input id="payment_date" type="date" name="payment_date" min="{{ $statement['closing_date'] }}" max="{{ now()->toDateString() }}" value="{{ old('payment_date', now()->toDateString()) }}" class="form-control @error('payment_date') is-invalid @enderror" required><x-field-error name="payment_date" /></div><button class="btn btn-primary w-100">Registrar pagamento</button><div class="form-text mt-2">Será criada uma transferência, não uma nova despesa.</div></form></div></div>@endif</div></div>
<div class="d-flex justify-content-between mt-4"><a href="{{ route('credit-cards.index') }}" class="btn btn-link"><i class="bi bi-arrow-left me-1"></i>Voltar</a>@if(!$card['archived'])<form method="post" action="{{ route('credit-cards.destroy', $card['id']) }}" data-confirm="Arquivar este cartão? Novas compras serão bloqueadas.">@csrf @method('delete')<button class="btn btn-outline-danger">Arquivar cartão</button></form>@endif</div>
@endsection
